[package]
name = "cargo-release-commit-message-issue"
version = "3.0.0"
edition = "2024"

[package.metadata.release]
pre-release-commit-message = "My Release Message: {{version}}"

[workspace]
members = ["crates/whatever"]
